<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>datetime</AssemblyName>
    <PackageId>CoreCli.DateTime</PackageId>
    <PackageDescription>Format the current date and time from the command line.</PackageDescription>
    <PackageTags>dotnet-tool;datetime;cli</PackageTags>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>datetime</ToolCommandName>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <None Update="README.md" Pack="true" PackagePath="\" />
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>CoreCli.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
